### PR TITLE
Add loongarch support for gstreamer

### PR DESCRIPTION
**Pull request by redeastcn**
Add loongarch support for gstreamer. Please review. THX.

### CODE REVIEW

**Comment by xen0n** [comment]
I'll add the fix straight into `::gentoo`, because it's so simple.

Also I've opened upstream MR for this: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2443

BTW, can you reply here your real name and email in `Zhang San <foo@example.com>` format, so I can properly mention you in the relevant places for your contribution?

**Comment by redeastcn** [comment]
That's great. My name is Chen Tao, redeast_cn@outlook.com. Thanks.

**Comment by xen0n** [comment]
`::gentoo` already has the build fix, and keyworded; please sync after a few hours and test. Thanks for the reporting again!

**Comment by xen0n** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/b6076d73949f291a077bfd80500512ac60c2b063

Your suggestion is now upstream!

**Pull request closed without merging**
